# use trusty beta to get a better C++ compiler for bcrypt
sudo: required
dist: trusty

# needed for mongo on trusty
group: edge

language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=test
services:
  - mongodb
